export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_PHOTOS = 'UPDATE_PHOTOS';

export const GET_TIMESERIES_DATA = 'GET_TIMESERIES_DATA';
export const INSERT_TIMESERIES_DATA = 'INSERT_TIMESERIES_DATA';
export const INSERT_LATEST_TOTAL_DATA = 'INSERT_LATEST_TOTAL_DATA';
export const GET_TIMESERIES_DATA_ERROR = 'GET_TIMESERIES_DATA_ERROR';

//Signup
export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Login
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

//export const LOGIN_EXISTING = 'LOGIN_EXISTING';
//export const LOGOUT = 'LOGOUT';
// Logout
export const LOGOUT_REQUESTING = 'LOGOUT_REQUESTING';


//UserData
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
